//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstSample
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [Serializable]
    [DataContract]
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.imageGalleries = new HashSet<imageGallery>();
            this.reminders = new HashSet<reminder>();
            this.topMessages = new HashSet<topMessage>();
            this.UserInGroups = new HashSet<UserInGroup>();
            this.abouts = new HashSet<about>();
            this.thisWeekTitles = new HashSet<thisWeekTitle>();
        }
        public Group(string name, string city, string street, int build, string phone, string mail, string fax)
        {
            this.name = name;
            this.city = city;
            this.build = build;
            this.phone = phone;
            this.mail = mail;
            this.fax = fax;
            this.streat = street;
            this.UserInGroups = new HashSet<UserInGroup>();
            this.imageGalleries = new HashSet<imageGallery>();
            this.reminders = new HashSet<reminder>();
            this.topMessages = new HashSet<topMessage>();
            this.UserInGroups = new HashSet<UserInGroup>();
            this.abouts = new HashSet<about>();
            this.thisWeekTitles = new HashSet<thisWeekTitle>();
        }

        [DataMember]
        public int id { get; set; }
        [DataMember]
        public string name { get; set; }
        [DataMember]
        public string city { get; set; }
        [DataMember]
        public string streat { get; set; }
        [DataMember]
        public Nullable<int> build { get; set; }
        [DataMember]
        public string phone { get; set; }
        [DataMember]
        public string mail { get; set; }
        [DataMember]
        public string fax { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<imageGallery> imageGalleries { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reminder> reminders { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<topMessage> topMessages { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInGroup> UserInGroups { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<about> abouts { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thisWeekTitle> thisWeekTitles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mainAboutTitle> mainAboutTitles { get; set; }
    }
}
