//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstSample
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [Serializable]
    [DataContract]
    public partial class UserInGroup
    {

        [DataMember]
        public string userMail { get; set; }
        [DataMember]
        public int groupId { get; set; }
        [DataMember]
        public bool isAdministrator { get; set; }
        [DataMember]
        public string childFirstName { get; set; }
        [DataMember]
        public string childLastName { get; set; }
        [DataMember]
        public string nickname { get; set; }
        [DataMember]

        public virtual Group Group { get; set; }
        [DataMember]
        public virtual User User { get; set; }
        public UserInGroup()
        {

        }
        public UserInGroup(
            int groupId,
            string mail,
            bool isAdministrator,
            string childFirstName,
            string childLastName,
            string nickname
            )
        {
            this.userMail = mail;
            this.groupId = groupId;
            this.isAdministrator = isAdministrator;
            this.childFirstName = childFirstName;
            this.childLastName = childLastName;
            this.nickname = nickname;
        }
    }
}
